### ISSUE TITLE
App Layout 2

### ISSUE THREAD

**Issue by mnibecker** [juttle/juttle-viewer#33]
A couple changes to app layout:
- Remove the right rail for inputs. Instead place inputs horizontally above the charts.
- Move the run button so it's on the left side.

**Comment by dmehra** [comment]
Additionally to the run button moving, the idea was to have an action bar on the top that would include: load, run, stop, "show juttle".

**Comment by mnibecker** [comment]
I think run & stop should be the same button, but either we should make that a separate ticket.
