### ISSUE TITLE
Button overhang in fullscreen mode

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-viewer#50]
When running in fullscreen mode (ie: having clicked the Expand button in upper-right corner), I see the play/unexpand buttons overhanging into the chart area. If the chart is a table, they can cover up some of the top line text. If the chart is a timechart, they partially block the series filter.

![image](https://cloud.githubusercontent.com/assets/5817365/13646841/33dcf802-e5e6-11e5-85b5-6c2dd7cf1327.png)

**Comment by mnibecker** [comment]
@dmehra any suggestions of where you would like the play button?

**Comment by dmehra** [comment]
My best idea was to lower the code/chart area so the buttons can fully fit above it without overlaying.

**Comment by mnibecker** [comment]
I was thinking something similar
