### ISSUE TITLE
Better error reporting in the viewer

### ISSUE THREAD

**Issue by jut-test** [juttle/juttle-viewer#8]
Avoid situations where juttle generates an error, but the viewer app won't tell us the details.
- show screen of death with stack trace for uncaught exceptions
- catch more (all?) exceptions and show meaningful errors in the viewer. 
This may be resolved by https://github.com/juttle/juttle-service/issues/19
- cover the case of https://github.com/juttle/outrigger/issues/112

**Comment by mnibecker** [comment]
resolved by #21
